### ISSUE TITLE
"pipeline queue empty" when running under high concurrency

### ISSUE THREAD

**Issue by peterbe** [fzzy/radix#50]
I get this error:
```
[negroni] PANIC: pipeline queue empty
goroutine 497 [running]:
github.com/codegangsta/negroni.func·003()
	/Users/peterbe/dev/GO/src/github.com/codegangsta/negroni/recovery.go:34 +0x10a
runtime.panic(0x2ec6a0, 0xc208000790)
	/opt/boxen/homebrew/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:248 +0x18d
main.errHndlr(0x70c1b0, 0xc208000790)
	/Users/peterbe/dev/GO/autocompeter/server.go:51 +0x127
main.func·002(0x711c00, 0xc208192280, 0xc2081384e0)
	/Users/peterbe/dev/GO/autocompeter/server.go:112 +0x4d6
net/http.HandlerFunc.ServeHTTP(0xc20803e5e0, 0x711c00, 0xc208192280, 0xc2081384e0)
	/opt/boxen/homebrew/Cellar/go/1.3.3/libexec/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc208022ff0, 0x711c00, 0xc208192280, 0xc2081384e0)
...
```
When running this code:
```go
	mux.HandleFunc("/v1", func(w http.ResponseWriter, req *http.Request) {
		q := strings.Trim(req.FormValue("q"), " ")

		terms := CleanWords(q)
		// NOTE! Maybe we don't need the ZINTERSTORE if there's only 1 command
		c.Append("ZINTERSTORE", "$tmp", len(terms), terms, "AGGREGATE", "max")
		c.Append("ZREVRANGE", "$tmp", 0, 10, "WITHSCORES")

		c.GetReply() // the ZINTERSTORE
		replies, err := c.GetReply().List()
		errHndlr(err)  # THIS is line 112 as mentioned in the stacktrace
```

I built a simple server (using negroni) and it works wonderfully except as soon as I try to benchmark some concurrency on it. E.g. `ab -n 1000 -c 10 http://localhost...`

I can provide more details if need be.

**Comment by mediocregopher** [comment]
I'm guessing in your example `c` is a global variable? If that's the case that explains your issue, the `redis.Client` isn't thread-safe, it's meant to be used in a single-threaded context. You probably want to check out the [pool](http://godoc.org/github.com/fzzy/radix/extra/pool) struct, which is thread-safe.

**Comment by peterbe** [comment]
I started a new branch to play with your "competitor" [redigo](https://github.com/garyburd/redigo) just to see what it was like. Very quickly I ran into the same problem there. They have it loud an clear on their [FAQ](https://github.com/garyburd/redigo/wiki/FAQ#is-redigo-thread-safe) though.

Time for me to explore this pool thing.
