### ISSUE TITLE
Cluster Connection Issue

### ISSUE THREAD

**Issue by joshuarubin** [fzzy/radix#52]
Forgive me, this may not be an issue with your package, but I thought you might have some advice either way.

We are trying to use your cluster package for our redis cluster where our redis nodes are running inside docker containers.

Our docker containers are always assigned a random IP address when started. We configure the cluster with a command like this:

```bash
./redis-trib create --replicas 1 172.17.8.101:7000 172.17.8.102:7000 172.17.8.103:7000
```

This is successful.

What then happens is that the `nodes.conf` file on some machines looks like this:

```
1221bc539aa268f9b4527709d5bf578bfcad531f 172.17.8.103:7000 master - 0 1424216410531 3 connected 10923-16383
fc935d969b0c2f90d11b2fa0b0055701b676182c 172.17.8.102:7000 master - 0 1424216409594 2 connected 5461-10922
138b3f6679f8a4a349a17c740c2692d48ca605d0 10.0.0.5:7000 myself,master - 0 0 1 connected 0-5460
```

The main problem is that the `myself` nodes use the internal docker IP address which will change and is not reachable outside the container.

This is not a problem when using `redis-cli`, which *always* works.

However, your cluster package, uses `CLUSTER SLOTS` which returns data like this:

```
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "172.17.8.103"
      2) (integer) 7000
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "172.17.8.102"
      2) (integer) 7000
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.0.0.5"
      2) (integer) 7000
```

There is no way to identify the `myself` node using this method and, because the `10.0.0.5` address is unreachable, the connection always hangs.

If we manually change the `nodes.conf` files to look like this, then things work as expected:

```
1221bc539aa268f9b4527709d5bf578bfcad531f 172.17.8.103:7000 master - 0 1424216410531 3 connected 10923-16383
fc935d969b0c2f90d11b2fa0b0055701b676182c 172.17.8.102:7000 master - 0 1424216409594 2 connected 5461-10922
138b3f6679f8a4a349a17c740c2692d48ca605d0 :7000 myself,master - 0 0 1 connected 0-5460
```

The problem with this is that if we reshard or make any changes, the `nodes.conf`file is overwritten and will use a new IP address for the `myself` line on each node.

Is there a way to either:

1. ensure that redis-trib.rb sets an empty IP for the `myself` line in `nodes.conf`? (It always seems that at least one node is configured this way, but I am not sure why).
2. update your cluster package to find a way to identify the `myself` node of `CLUSTER SLOTS` so that the current connection node ip is used? Note, that this is made even more tricky because we have a load balancer that redirects port 6379 to any node's port 7000, so a connection to ip address 172.17.8.101:6379 may actually be routed to the node at 172.17.8.103:7000.

Thanks for your help!

**Comment by mediocregopher** [comment]
Strangely, you are actually asking the right guy! sorta... I actually posted about this exact issue on the redis group:

https://groups.google.com/forum/#!topic/redis-db/ZLOKATn6vZc

Unfortunately no one answered, and as far as I can tell there's no way way around it. If you want to bump that thread we might be one step closer to wringing a proper answer out of this :P

**Comment by mediocregopher** [comment]
Although looking more closely at your output I see we got slightly different results. I was seeing all nodes as using their internal docker ips, for you only the node you're looking at returns it. I wonder what we did differently

**Comment by joshuarubin** [comment]
I did find that thread before posting this issue, guess we are going in circles together then...

One option that may work for you is to use the `docker run --net host` option so that the network is not virtualized in the docker container.

This doesn't work in our environment though because our load balancers are configured based on the ports that the docker containers are listening to and with `--net host` the containers don't explicitly listen on any ports.

You are correct that our `nodes.conf` files are slightly different. I definitely reliably get the public ips for the "non-`myself`" nodes.

On the `myself` nodes, about 1/3 get no IP at all and the other 2/3 get the docker0 ip address.

We are using [this docker image](https://registry.hub.docker.com/u/zvelo/redis-trib/) to run `redis-trib.rb`, so that `redis-trib.rb` is actually being run from a container insider the docker0 network of one of the hosts.

I have a few questions for you that you may have figured out already though:

1. Do you know if manually editing `nodes.conf` as I described is a reliable fix?
2. Do we have to restart redis after making the change?
3. Is there any redis cluster command to make the change (once per node) so that a restart is not required?
4. Do you know if this is an issue with `redis-trib.rb` or the redis server?

Sorry for peppering you with questions, but any help you can provide would be great. Thank you so much!

**Comment by mediocregopher** [comment]
1) I really doubt it, but I don't actually know

2) I don't *think* so. I haven't tested it though

3) Not that I'm aware of

4) Most likely server side, redis-trib isn't really doing anything special except calling particular cluster commands, of which there aren't actually that many

I'm going to play with this some more tonight, specifically try out the responder in that email thread's suggestion about messing with bind. I'll post in there if I come up with anything more
