### ISSUE TITLE
Cmd().Str() sometimes fails strangely

### ISSUE THREAD

**Issue by peterbe** [fzzy/radix#54]
So I'm doing this:
```go
var title string
title, err = c.Cmd("HGET", "foo", "bar").Str()
```
That works if `HGET foo bar` does **have something in Redis**. 
However, **if it doesn't** you get this:
```go
error: string value is not available for this reply type
```
This is a panic error.

**Comment by peterbe** [comment]
I thought I'd try doing:
```go
var title string
reply := c.Cmd("HGET", "foo", "bar")
```
But `reply.Err` is `nil` no better if the key exists or not. It's always `nil`.

**Comment by mediocregopher** [comment]
Hi peter! The reason for this is that if HGET encounters a key or field which doesn't exist it returns Nil, which is not a string. If it's possible for your key/field to not exist you should first check if `reply.Type == redis.NilReply`.
