### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mohamedattahri** [fzzy/radix#56]
Hello,

The behavior of radix sometimes becomes erratic when the number of `GET` commands per second for the same key increases. I frequently get "Parse Error" reply errors, but sometimes it panics with error `runtime error: slice bounds out of range`.

Below is my stack trace:

```json
[
    {"file":"/Users/mohamed/Go/src/github.com/fzzy/radix/redis/client.go","line":146,"func":"github.com/fzzy/radix/redis.(*Client).parse"},
    {"file":"/Users/mohamed/Go/src/github.com/fzzy/radix/redis/client.go","line":122,"func":"github.com/fzzy/radix/redis.(*Client).readReply"},
    {"file":"/Users/mohamed/Go/src/github.com/fzzy/radix/redis/client.go","line":67,"func":"github.com/fzzy/radix/redis.(*Client).Cmd"}
]
```

**Comment by mediocregopher** [comment]
Hi mohamed! If you're using the same `radix.Client` from multiple go routines that would certainly explain this behavior. If this is the case you should check out the [pool](http://godoc.org/github.com/fzzy/radix/extra/pool) package which will help I hope.

If that's not the case, could you check that you have the latest radix pulled and maybe provide a small code sample which produces the problem for you? I have used radix under extremely high load many times and haven't run into this problem.

Thanks!

**Comment by mohamedattahri** [comment]
Thanks Brian! I'll check out the pool package and get back to you. 

Might not be a bad thing to return an explicit error instead of the letting the program panic though.

**Comment by mohamedattahri** [comment]
You were right Brian. Using the pool package fixes the issue. Thank you so much.

**Comment by mediocregopher** [comment]
Sorry for the late reply, happy to help! :)
