### ISSUE TITLE
Executing HGET on non-existing key closes connection

### ISSUE THREAD

**Issue by phillipCouto** [fzzy/radix#57]
When I issue an HGET on a non-existing key the connection is closed even though redis is just returning NIL.

Is this by design?

**Comment by phillipCouto** [comment]
The logic for the connection kill is in [clieng.go#L167](https://github.com/fzzy/radix/blob/master/redis/client.go#L167).

**Comment by mediocregopher** [comment]
Hey Phillip! This is definitely not the intended behavior, and that code only ever fires if there's been an actual network level error (regardless of what is happening on the application level). ReadMessage only  returns an error on an actual network level error as well.

Was this a one-time error that you saw? If so it might have just been coincidence. If not, could you maybe provide some sample code that causes this to happen for you? Also, can you make sure you've pulled radix and are up-to-date with master?

Thanks!

**Comment by phillipCouto** [comment]
It was consistently happening. I will dig into it further and see if I can write a small piece of code to reproduce the issue.

**Comment by mediocregopher** [comment]
Were you ever able to reproduce this? If so I'd definitely want to take a look, but if you were able to resolve it I'd like to close this issue :)

**Comment by phillipCouto** [comment]
I was able to avoid the issue and haven't had a chance to double back and try to reproduce.

I was pulled to a different project but once I get back to the project using the library I will try to reproduce the issue.

So now I say we close the issue and I will open it again later with more accurate information.

**Comment by mediocregopher** [comment]
Awesome, thanks!
