### ISSUE TITLE
Question: How to check if the connection is "sane"

### ISSUE THREAD

**Issue by Dynom** [fzzy/radix#62]
Hi,

I'm fairly new to Go, so I might be asking a silly question, but here goes.

I try to reuse a sane connection, by using the following code:
```go
  var client *redis.Client

  // ..

  // If Conn is of type net.Conn, it's initialised (or so I assume).
  if _, ok := c.client.Conn.(net.Conn); ok {

    // Test if our connection is valid by attempting a 0 byte read
    // If so, we re-use this client
    zero := make([]byte, 0)
    if _, err := c.client.Conn.Read(zero); err == nil || err == io.EOF {
      return c.client, nil
    }
  }

  // ..

  // Connect to our Redis backend
  log.Print("Attempting to connect to our Redis backend...")
  client, err = redis.DialTimeout("tcp", "localhost:6379", time.Duration(time.Millisecond*500))
  if err == nil {
    log.Print("Connected to our Redis backend!")
    break
  }

  // ..

  c.client = client
  return c.client
```

This code fails, because of the type check `if _, ok := c.rClient.Conn.(net.Conn); ok {`. How would I go about checking if `c.client` is initialised and ready to be re-used?

The error I get now is: `runtime error: invalid memory address or nil pointer dereference`

I'm currently working around this issue by doing the following on my factory:
```go
func NewClaimer() *Claimer {
	return &Claimer{client: new(redis.Client)}
}
```
But that doesn't "feel" right.

**Comment by mediocregopher** [comment]
Hi Dynom! I'm a little confused by what exactly you're trying to accomplish, but hopefully I can help out. Generally in go it's very rare to initialize a struct using `new`. For structs whose only purpose is to contain some fields and you want a "blank" instance it works, but in cases like this where you're working with another package's types you want to stick to that package's exposed initializer methods to create your struct instances. In this case those would be [redis.Dial](https://godoc.org/github.com/fzzy/radix/redis#Dial), [redis.DialTimeout](https://godoc.org/github.com/fzzy/radix/redis#DialTimeout), or any other method which returns a `*redis.Client` (like [pool.Get](https://godoc.org/github.com/fzzy/radix/extra/pool#Pool.Get)). At the point you get a `*redis.Client` it will be initialized and connected.

If you want to later check if a client is still connected and working doing a simple PING command should suffice:

```
if err := client.Cmd("PING").Err; err != nil {
    // client is not alive
}
```

Hopefully that's helpful, but if not I'd be curious what your exact use-case is and why you're trying to initialize a zeroed `*redis.Client` as opposed to using one of the dial functions.

**Comment by Dynom** [comment]
Hi @mediocregopher, thanks for replying so quickly. I read my question again and I totally understand that you might not follow my line of thought (-:

Basically I try to share the connection. I'll try to explain it using the flow I'd like to create:

1. Check if we have an initialised library, ready to process our commands. If we do, return it
2. If we don't have a connection ready, construct/initialise one and return that

I don't want to use `new(redis.Client)`, but I see no other way to check if the client is initialised without actually connecting. I can't perform a PING, because it's too early for that, I haven't even "dialed out" yet. Maybe that's an anti-design, but I feel I'm working around something the library should offer me.

So in (somewhat) short: What I'm looking for is a way to properly construct a client, without actually connecting to the Redis backend. 

Just to sketch an outline of the code:
```go
func NewClaimer() *Claimer {
    return &Claimer{}
}

func (c *claimer) Claim(..) error {
    client := c.connect()
    // do stuff with client
    return result
}

func (c *claimer) connect() {
    // if c.client is initialised, reuse our constructed client
    return c.client

    // ..

    // if not, initialise c.client and return that
    c.client = redis.DialTimeout("tcp", "localhost:6379", time.Duration(time.Millisecond*500))

    // ..

    return c.client
}
```

Maybe this is the wrong approach and I should move the Radix library outside this struct and pass it along. But I don't want my application to know too much about it's persistency layer and this way it's fairly isolated.

**Comment by mediocregopher** [comment]
i'm assuming `Claimer` looks something like this:

```go
type Claimer struct {
    client *redis.Client
}
```

Then your connect method could be as simple as:

```go
func (c *Claimer) connect() (*redis.Client, error) {                             
    if c.client == nil {                                                         
        var err error                                                            
        c.client, err = redis.DialTimeout("tcp", "localhost:6379", 500 * time.Millisecond)
        return c.client, err                                                     
    }                                                                             
    return c.client, nil                                                                                               
}
```

However you mention that purpose here is to share the connection. If you simply mean to use it more than once within the same go routine then this is approach will work fine, but if you're meaning for more than one goroutine to interact with the `Claimer`, potentially at the same time, you'll need to use a [pool](https://godoc.org/github.com/fzzy/radix/extra/pool), as the `*redis.Client` on its own is not thread-safe.

**Comment by Dynom** [comment]
Hi @mediocregopher,

It's starting to make sense now. I was looking for a pool, but I didn't find it. Which is possibly even more silly now that I found it in extra..

Thanks for your time and patience, this helps me on the right track!
