### ISSUE TITLE
Cannot set expiration with SET command

### ISSUE THREAD

**Issue by alexcesaro** [fzzy/radix#67]
```go
package main

import (
	"fmt"

	"github.com/fzzy/radix/redis"
)

func main() {
	c, err := redis.Dial("tcp", ":6379")
	if err != nil {
		panic(err)
	}
	r := c.Cmd("SET", "a", "a", "EX 3600")
	fmt.Println(r.Err)
}
```
On my machine, this program outputs: `ERR syntax error`. While it works fine if I remove the "EX 3600" parameter.

My Redis version:
```
$ redis-server --version
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9
$ redis-cli
127.0.0.1:6379> SET a a EX 3600
OK
```

**Comment by alexcesaro** [comment]
I just found that it works when I use `c.Cmd("SET", "a", "a", "EX", "3600")`. Is it intended?

**Comment by mediocregopher** [comment]
This isn't really to do with the driver, it's simply how redis works. Your
command is sent to redis as an array. When using redis-cli it automatically
splits into an array on spaces (unless you explicitly wrap in quotes),
while in the driver your simply giving the array elements

**Comment by alexcesaro** [comment]
Ok but in the Redis doc, setting the expiration looks like one argument not two. I think there should be an example somewhere in the doc because it is not very intuitive.

**Comment by mediocregopher** [comment]
Unfortunately the redis project and its documentation are separate from
this one, so I can't really make any changes to their docs. I could modify
the docs for radix a bit maybe, I just don't want to over document

**Comment by alexcesaro** [comment]
I am not sure adding one sentence in `Cmd` description and / or adding one more command in the "Cmd and Reply" example would be over documenting :-)
That is your call, but I am quite confident it would help other people.

**Comment by mediocregopher** [comment]
So what I did was went ahead and replaced one of the examples in the Cmd and Reply section with one which demonstrates this behavior better. If more people come forward having this issue I'll go ahead and add a more explicit explanation of what's going on. Thanks for submitting the issue!

**Comment by alexcesaro** [comment]
Perfect :+1:
