### ISSUE TITLE
Garbled error msg

### ISSUE THREAD

**Issue by ivababukova** [fzzy/radix#69]
the following code run against 3528e87a910c6730810cec1be187f989d7d9442a produces the following garbled error msg:
`errora:  (0x7fe58d067780,0xc20800a4f0)`

---
    
    import "github.com/fzzy/radix/redis"
    
    func main() {
    	client, err := redis.Dial("tcp", "localhost:6379")
    	if err != nil {
    		println("error! could not coonect to db")
    	} else {
    		client.Cmd("SET", "foo", "bar")
                        reply, err2 := client.Cmd("EVAL", "return 1", 0).Str()
		        if err2 != nil {
    			println("errora: ", err2)
    		}
    		fmt.Println(reply)
    	}
    }

**Comment by ivababukova** [comment]
FYI it's probably a memory corruption. Semantically identical piece of code returns a valid error message:

    func main() {
    	ugqb := queryBuilder.QueryBuilder{}
    	var query []string
    	query = ugqb.InitGame("a01de45a674ad007a9abcf57b094a2a3", `{"move":true}`)
   	query = query
    	client, err := redis.Dial("tcp", "localhost:6379")
   			
         replya, errora := client.Cmd("EVAL", "return 1", 0).Str()
    	fmt.Println(err, replya, "asd", errora)
    	err = err
    }

**Comment by mediocregopher** [comment]
Thanks for the good case reports :) In this case the issue is in the use of `println`, which does very minimal formatting, and really shouldn't be used at all. In your original example if you replace your `println`s with `fmt.Println` the correct output shows up. Hope this helps, let me know if you have any other issues :)

**Comment by ivababukova** [comment]
You are correct, this is not a bug, thanks for your comment.
