### ISSUE TITLE
Default database for new redis client?

### ISSUE THREAD

**Issue by tanmayzyp** [fzzy/radix#74]
I am creating a new redis client (conn). My question is- will it select database-0 by default or do I need to explicitly mention `conn.Cmd("select", 0)` ?

**Comment by mediocregopher** [comment]
By default all fresh redis connections should get database 0 (unless
there's some redis server configuration which allows this to be different,
but I don't think there is).

To directly answer your question, radix is not calling "select"
automatically for you, if you're wanting to work with db 0 you more than
likely don't need to do anything manually either.

**Comment by tanmayzyp** [comment]
Great!
Thank you @mediocregopher  for the clarification. 
Closing the issue.
