### ISSUE TITLE
How to handle sentinel client failover?

### ISSUE THREAD

**Issue by kuangchanglang** [fzzy/radix#77]
Hey guys, how can I deal with sentinel instance fail-over, in which circumstance GetMaster always returns a ClientError. 
Do I have to close that sentinel and try another one manually? Any better solutions?

**Comment by mediocregopher** [comment]
> Do I have to close that sentinel and try another one manually?

Unfortunately yes, I think calling `Close` and remaking the client again is the only solution this package provides.

I would encourage you in general to check out the [radix.v2](https://github.com/mediocregopher/radix.v2) package. It's actively supported and developed and in many ways is much easier to use than this one, as well as being faster. Unfortunately it probably won't make this particular problem any easier to solve, as the sentinel package remained largely the same =/

**Comment by kuangchanglang** [comment]
Thank you very much! You save my day. @mediocregopher
