### ISSUE TITLE
Cluster package also needs to get AUTH as pool.NewCustomPool

### ISSUE THREAD

**Issue by zhaoyuxi** [fzzy/radix#78]
The AUTH feature as following misses in Cluster package. We needs it.
// The following is an example of using NewCustomPool to have all connections
// automatically get AUTH called on them upon creation
//
// 	df := func(network, addr string) (*redis.Client, error) {
// 		client, err := redis.Dial(network, addr)
// 		if err != nil {
// 			return nil, err
// 		}
// 		if err = client.Cmd("AUTH", "SUPERSECRET").Err; err != nil {
// 			client.Close()
// 			return nil, err
// 		}
// 		return client, nil
// 	}
// 	p, _ := pool.NewCustomPool("tcp", "127.0.0.1:6379", 10, df)
//
func NewCustomPool(network, addr string, size int, df DialFunc) (*Pool, error) {

So I did a modification as following:
type Opts struct {
    // Support custome auth. 
    Dial pool.DialFunc
}
func (c *Cluster) newPool(addr string, clearThrottle bool) (*pool.Pool, error) {
        // Support custome auth. 
	df := c.o.Dial
	if df == nil {
		df = func(network, addr string) (*redis.Client, error) {
			return redis.DialTimeout(network, addr, c.o.Timeout)
		}
	}
}

Can support it in cluster directly?

**Comment by mediocregopher** [comment]
The `cluster.Opts` type already has a `Dialer` field on it for just this very purpose, that plus `cluster.NewWithOpts` should work. If you're not seeing that maybe you just need to pull?

**Comment by zhaoyuxi** [comment]
Yes. Thanks for your reply.
